from heapq import heappush, heappop
from random import random
import random
import pygame
from pygame import Rect
import time
import heapq
from copy import deepcopy

from agent import plan_next_move


class GridGame:
    def __init__(self, rows=50, cols=50, cell_size=14, render_delay=0.1):
        self.rows = rows
        self.cols = cols
        self.cell_size = cell_size
        self.screen_size = self.screen_size = (cols * cell_size, rows * cell_size)
        self.delay = render_delay

        # Colors
        self.COLOR_WALL = (139, 69, 19)  # brown
        self.COLOR_FLOOR = (169, 169, 169)  # gray
        self.COLOR_PLAYER = (255, 255, 0)  # yellow
        self.COLOR_GOBLIN = (0, 255, 0)  # green
        self.COLOR_EXIT = (255, 0, 0)  # red
        self.COLOR_GRID = (0, 0, 0)  # black grid lines
        self.BLACK = self.COLOR_GRID
        self.WHITE = (255, 255, 255)  # white


        # Player position
        self.pos = [0, 0]

        # Pygame setup
        pygame.init()
        pygame.display.init()
        self.screen = pygame.display.set_mode(self.screen_size)
        pygame.display.set_caption("Maze")
        self.clock = pygame.time.Clock()

        # Generate dungeon map
        self.grid = self._generate_maze()

        # Find player and exit
        self.player_pos = self._find_spawn()
        self.exit_pos = self._place_exit()
        self.goblin_pos = self._place_goblin()

        # Generate reward grid
        self.reward_grid = self._generate_reward_grid()

    def _draw_grid(self):
        for row in range(self.rows):
            for col in range(self.cols):
                rect = Rect(col * self.cell_size,
                            row * self.cell_size,
                            self.cell_size,
                            self.cell_size)

                # Choose color based on tile type
                tile = self.grid[row][col]
                if [row, col] == self.player_pos:
                    color = self.COLOR_PLAYER
                elif [row, col] == self.exit_pos:
                    color = self.COLOR_EXIT
                elif [row, col] == self.goblin_pos:
                    color = self.COLOR_GOBLIN
                elif tile == "W":
                    color = self.COLOR_WALL
                else:
                    color = self.COLOR_FLOOR

                pygame.draw.rect(self.screen, color, rect)
                pygame.draw.rect(self.screen, self.COLOR_GRID, rect, width=1)
       # pygame.display.flip()

    def _generate_maze(self):
        """
        Generates a dungeon/map by building a 2D python list.
        The list is of size self.rows by self.cols. This method
        generates each entry of the list 1 at a time. For each
        entry, it will assign it the string "F" with 0.75 probability,
        denoting that cell as a floor. With 0.25 probability, it will
        assign it the string "W", denoting it as a Wall.
        """
        grid = []
        for row in range(self.rows):
            grid_row = []
            for col in range(self.cols):
                # Randomly choose wall or floor
                if random.random() < 0.25:  # 25% chance of wall
                    grid_row.append("W")
                else:
                    grid_row.append("F")
            grid.append(grid_row)
        return grid

    def _find_spawn(self):
        """
        Locates all valid spawning cells for the agent in the left region
        of the dungeon/maze generated by _generate_maze(), and then randomly selects one as the
        spawn point. A valid spawn cell is any cell that isn't a wall.
        """
        potential_spawns = []
        for row in range(self.rows):
            for col in range(5):  # only check first 5 columns
                if self.grid[row][col] == "F":
                    potential_spawns.append([row, col])
        return random.choice(potential_spawns)

    def _place_exit(self):
        """
        Locates all valid exit cells for the agent in the right region
        of the dungeon/maze generated by _generate_maze(), and then randomly selects one as the
        exit point. A valid exit cell is any cell that isn't a wall.
        """
        potential_exits = []
        for row in range(self.rows - 1, -1, -1):
            for col in range(self.cols - 1, self.cols - 6, -1):
                if self.grid[row][col] == "F":
                    potential_exits.append([row, col])
        return random.choice(potential_exits)

    def _place_goblin(self):
        """
        Locates all valid goblin spawn cells in the middle region of the
        dungeon/maze generated by _generate_maze(), and then randomly selects
        one as the goblin spawn. A valid spawn cell is any cell that isn't a wall.
        """
        potential_goblin_spawns = []
        for row in range(self.rows // 3, 2 * self.rows // 3):
            for col in range(self.cols // 3, 2 * self.cols // 3):
                if self.grid[row][col] == "F":
                    potential_goblin_spawns.append([row, col])
        return random.choice(potential_goblin_spawns)
    
    def _generate_reward_grid(self):
        """
        This method looks at the maze generated by _generate_maze() and creates
        a grid of rewards. Rewards on the grid are associated with their respective
        locations in the maze. For example, the reward stored at row 5 column 3 is
        the reward for being at row 5 column 3.
        """
        if self.grid == None: # Make sure a maze has been generated first
            return None
        
        # Initialize Reward Grid
        reward_grid = deepcopy(self.grid)

        for row in range(self.rows):
            for col in range(self.cols):
                if reward_grid[row][col] == "W": # -100000 Reward for Walls
                    reward_grid[row][col] = -100000
                elif abs(self.goblin_pos[0] - row) <= 5 and abs(self.goblin_pos[1] - col) <= 5: # Reward for being near goblin is based on distance
                    reward_grid[row][col] = min(-10 - abs(self.goblin_pos[0] - 5), -10 - abs(self.goblin_pos[1]))
                elif [row, col] == self.exit_pos: # Reward for winning is really large
                    reward_grid[row][col] == 10000
                else:
                    reward_grid[row][col] = 1 # Reward for a normal state is small but positive
        return reward_grid

    def execute(self, command, entity="PLAYER"):
        if command is None:
            return

        if entity == "PLAYER":
            pos = self.player_pos
        elif entity == "GOBLIN":
            pos = self.goblin_pos
        else:
            return

        if command == "UP" and pos[0] > 0 and self.grid[pos[0] - 1][pos[1]] != "W":
            pos[0] -= 1
        elif command == "DOWN" and pos[0] < self.rows - 1 and self.grid[pos[0] + 1][pos[1]] != "W":
            pos[0] += 1
        elif command == "LEFT" and pos[1] > 0 and self.grid[pos[0]][pos[1] - 1] != "W":
            pos[1] -= 1
        elif command == "RIGHT" and pos[1] < self.cols - 1 and self.grid[pos[0]][pos[1] + 1] != "W":
            pos[1] += 1


    def display_move(self, move, entity):
        self.execute(move, entity=entity)  # update agent position
        self._draw_grid()  # redraw the grid
        pygame.display.flip()
        time.sleep(self.delay)



game = GridGame()


def manhattan_distance_bad(pos1, pos2):
    """
    - This function calculates an intentionally suboptimal heuristic for the A* algorithm.
    - In the case of this program, we ensure a suboptimal heuristic by adding noise(20-40% error) to the heuristic.
    - The goal of this "bad" heuristic is to make the goblin's pathfinding more "imperfect" so that there's some variance
      in the A* algorithms of the agent and the goblin, making the game more interesting visually.

    :param pos1: position of first agent
    :param pos2: position of second agent
    :return: Manhattan distance between the two agents
    """
    dx = abs(pos1[0] - pos2[0])
    dy = abs(pos1[1] - pos2[1])
    manhattan = dx + dy


    # The reason uniform distribution was used was so that we have a variance in random noise chance
    # This is the main reason the "noise" works, making the goblin stupid
    noise = random.uniform(0.2, 0.4) * manhattan
    return manhattan + noise

def move_goblin_towards_agent(self, random_chance):
    """
    Moves the goblin towards the player agent using a modified A* algorithm with an intentional chance of random movement.
    
    :param self: The GridGame instance for accessing the goblin, player, and grid. 
    :param random_chance: An integer (1-100) defining the percentage probability (e.g., 20 = 20%) 
                          for the goblin to make a random valid move instead of following the heuristic path.
    :return: The updated position of the goblin.
    """

    if random.randint(1, 100) <= random_chance:
        goblin_row, goblin_column = self.goblin_pos
        potential_moves = [
            ([goblin_row - 1, goblin_column], "UP"),
            ([goblin_row + 1, goblin_column], "DOWN"),
            ([goblin_row, goblin_column - 1], "LEFT"),
            ([goblin_row, goblin_column + 1], "RIGHT")
        ]

        valid_moves = [
            cmd for pos, cmd in potential_moves
            if 0 <= pos[0] < self.rows and 0 <= pos[1] < self.cols and self.grid[pos[0]][pos[1]] != "W"
        ]

        if valid_moves:
            return random.choice(valid_moves)
        return None #No random moves

    # A* implementation:
    start = tuple(self.goblin_pos)
    player_position = tuple(self.player_pos)


    open_set = []
    heappush(open_set, (manhattan_distance_bad(start, player_position), 0, start, [start]))

    visited = set()

    while open_set:
        f_score, g_score, current, path = heappop(open_set)

        # If we reached the agent, return only the first move in the path
        if current == player_position:
            if len(path) > 1:
                # Take only the first step from the path
                next_pos = path[1]
                current_pos = self.goblin_pos

                if next_pos[0] < current_pos[0]:
                    return "UP"
                elif next_pos[0] > current_pos[0]:
                    return "DOWN"
                elif next_pos[1] < current_pos[1]:
                    return "LEFT"
                elif next_pos[1] > current_pos[1]:
                    return "RIGHT"
                return None  # Already at goal

        if current in visited:
            continue
        visited.add(current)

        # Explore possible neighbors
        row, column = current
        neighbors = [
            (row - 1, column),  # Up
            (row + 1, column),  # Down
            (row, column - 1),  # Left
            (row, column + 1)  # Right
        ]

        for neighbor in neighbors:
            n_row, n_column = neighbor

            # Check if neighbor is valid
            if (0 <= n_row < self.rows and
                    0 <= n_column < self.cols and
                    self.grid[n_row][n_column] != "W" and
                    neighbor not in visited):
                new_g_score = g_score + 1
                new_f_score = new_g_score + manhattan_distance_bad(neighbor, player_position)
                new_path = path + [neighbor]

                heappush(open_set, (new_f_score, new_g_score, neighbor, new_path))

    # If no path found, the goblin stays in place
    return None

if __name__ == "__main__":
    # Initialize the game
    game = GridGame(rows=50, cols=50, cell_size=14, render_delay=0.08)


    # Example goal and goblin positions
    goal = game.exit_pos
    goblin_pos = game.goblin_pos

    running = True
    while running:
        next_move = plan_next_move(game.player_pos, goal, goblin_pos, grid=game.grid)
        game.display_move(next_move, entity="PLAYER")

        goblin_move = move_goblin_towards_agent(game, 20)
        game.display_move(goblin_move, entity="GOBLIN")

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

            if event.type == pygame.QUIT:
                running = False

            if event.type == pygame.KEYDOWN:
                if event.key == pygame.K_UP:
                    game.execute("UP")
                elif event.key == pygame.K_DOWN:
                    game.execute("DOWN")
                elif event.key == pygame.K_LEFT:
                    game.execute("LEFT")
                elif event.key == pygame.K_RIGHT:
                    game.execute("RIGHT")


        if game.player_pos == goal:
            print("Goal reached!")
            running = False
        if game.player_pos == goblin_pos:
            print("Caught by goblin!")
            running = False





# game = GridGame()
# if __name__ == "__main__":
#     running = True
#     while running:
#         for event in pygame.event.get():
#             if event.type == pygame.QUIT:
#                 running = False

#         game._draw_grid()
#         pygame.display.flip()
